/**************************************************************************
 *     This file is part of MataHari2020.

    I, Dick Hamill, the author of this program disclaim all copyright
    in order to make this program freely available in perpetuity to
    anyone who would like to use it. Dick Hamill, 6/1/2020

    MataHari2020 is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    MataHari2020 is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    See <https://www.gnu.org/licenses/>.

    13JUL2026 Bug Fixes: Commented out unused chime types and added mata Hari specific chime states
    John Kriz (KrizAkoni@gmail.com)
 */

#define MATAHARI2020_NUM_CHIMES


struct ChimeEntry {
  byte SoundEffectNum;
  byte SolNumber;
  byte TimeOffset;
};

struct ChimeEntry MataHariSFXLowPriorityLevel1[] = {
  {SOUND_EFFECT_AB_LANE_1,SOL_CHIME_100, 0},
  {SOUND_EFFECT_AB_LANE_2,SOL_CHIME_100, 0}, 
  {SOUND_EFFECT_BONUS_COUNT, SOL_CHIME_1000, 0},
  {SOUND_EFFECT_2X_BONUS_COUNT, SOL_CHIME_1000, 0},
  {SOUND_EFFECT_3X_BONUS_COUNT, SOL_CHIME_1000, 2},
  {SOUND_EFFECT_5X_BONUS_COUNT, SOL_CHIME_1000, 2},
  {SOUND_EFFECT_INLANE, SOL_CHIME_10, 0},
  {SOUND_EFFECT_INLANE, SOL_CHIME_100, 2},
  //{SOUND_EFFECT_INLANE_UNLIT, SOL_CHIME_10, 0},
  //{SOUND_EFFECT_INLANE_UNLIT, SOL_CHIME_100, 2},
  {SOUND_EFFECT_OUTLANE_UNLIT, SOL_CHIME_100, 0},
  {SOUND_EFFECT_OUTLANE_UNLIT, SOL_CHIME_10, 2},
  //{SOUND_EFFECT_INLANE_LIT, SOL_CHIME_10, 0},
  //{SOUND_EFFECT_INLANE_LIT, SOL_CHIME_100, 2},
  {SOUND_EFFECT_OUTLANE_LIT, SOL_CHIME_100, 0},
  {SOUND_EFFECT_OUTLANE_LIT, SOL_CHIME_10, 2},
  {SOUND_EFFECT_OUTLANE_LIT, SOL_CHIME_100, 4},
  {SOUND_EFFECT_SKILL_SHOT, SOL_CHIME_10, 0},
  {SOUND_EFFECT_SKILL_SHOT, SOL_CHIME_100, 2},
  {SOUND_EFFECT_EXTRA_BALL, SOL_CHIME_10000, 0},
  {SOUND_EFFECT_DROP_TARGET, SOL_CHIME_100, 0},
  {SOUND_EFFECT_SAUCER, SOL_CHIME_100, 0},
  {SOUND_EFFECT_TILT_WARNING, SOL_CHIME_100, 0},
  {SOUND_EFFECT_TILT_WARNING, SOL_CHIME_10, 2},
  {SOUND_EFFECT_WIZARD_SCORE, SOL_CHIME_10000, 0},
  {SOUND_EFFECT_WIZARD_SCORE, SOL_CHIME_10000, 4},
  {SOUND_EFFECT_WIZARD_SCORE, SOL_CHIME_10000, 8},
  {SOUND_EFFECT_BUMPER, SOL_CHIME_10, 0},
  {SOUND_EFFECT_BUMPER_10, SOL_CHIME_10, 0},
  {SOUND_EFFECT_BUMPER_LIT, SOL_CHIME_100, 0},
  {SOUND_EFFECT_WIZARD_TIMER, SOL_CHIME_100, 0},
  {SOUND_EFFECT_10PT_SWITCH, SOL_CHIME_10, 0},
  {SOUND_EFFECT_SLING_SHOT, SOL_CHIME_10, 0}
};


struct ChimeEntry MataHariSFXLowPriorityLevel2[] = {
  {SOUND_EFFECT_AB_LANE_1, SOL_CHIME_100, 2},
  {SOUND_EFFECT_AB_LANE_1, SOL_CHIME_100, 4},
  {SOUND_EFFECT_AB_LANE_1, SOL_CHIME_100, 6},
  {SOUND_EFFECT_AB_LANE_1, SOL_CHIME_100, 8},
  {SOUND_EFFECT_AB_LANE_2, SOL_CHIME_100, 2},
  {SOUND_EFFECT_AB_LANE_2, SOL_CHIME_100, 4},
  {SOUND_EFFECT_AB_LANE_2, SOL_CHIME_100, 6},
  {SOUND_EFFECT_AB_LANE_2, SOL_CHIME_100, 8},
  {SOUND_EFFECT_2X_BONUS_COUNT, SOL_CHIME_10000, 2},
  {SOUND_EFFECT_3X_BONUS_COUNT, SOL_CHIME_100, 0},
  {SOUND_EFFECT_3X_BONUS_COUNT, SOL_CHIME_10000, 4},
  //{SOUND_EFFECT_INLANE_LIT, SOL_CHIME_1000, 6},
  //{SOUND_EFFECT_INLANE_LIT, SOL_CHIME_1000, 9},
  //{SOUND_EFFECT_INLANE_LIT, SOL_CHIME_1000, 12},
  //{SOUND_EFFECT_INLANE_LIT, SOL_CHIME_1000, 15},
  //{SOUND_EFFECT_INLANE_LIT, SOL_CHIME_1000, 18},
  {SOUND_EFFECT_SKILL_SHOT, SOL_CHIME_10, 4},
  {SOUND_EFFECT_SKILL_SHOT, SOL_CHIME_1000, 6},
  {SOUND_EFFECT_SKILL_SHOT, SOL_CHIME_1000, 7},
  {SOUND_EFFECT_SKILL_SHOT, SOL_CHIME_1000, 8},
  {SOUND_EFFECT_SKILL_SHOT, SOL_CHIME_1000, 9},
  {SOUND_EFFECT_SKILL_SHOT, SOL_CHIME_1000, 10},
  {SOUND_EFFECT_SKILL_SHOT, SOL_CHIME_1000, 11},
  {SOUND_EFFECT_EXTRA_BALL, SOL_CHIME_10000, 2},
  {SOUND_EFFECT_EXTRA_BALL, SOL_CHIME_10000, 4},
  {SOUND_EFFECT_EXTRA_BALL, SOL_CHIME_10000, 6},
  {SOUND_EFFECT_EXTRA_BALL, SOL_CHIME_10000, 8},  
  {SOUND_EFFECT_DROP_TARGET, SOL_CHIME_100, 2},
  {SOUND_EFFECT_DROP_TARGET, SOL_CHIME_100, 4},
  {SOUND_EFFECT_DROP_TARGET, SOL_CHIME_100, 6},
  {SOUND_EFFECT_DROP_TARGET, SOL_CHIME_100, 8},
  {SOUND_EFFECT_SAUCER, SOL_CHIME_100, 2},
  {SOUND_EFFECT_SAUCER, SOL_CHIME_100, 4},
  {SOUND_EFFECT_SAUCER, SOL_CHIME_100, 6},
  {SOUND_EFFECT_SAUCER, SOL_CHIME_100, 8}, 
  {SOUND_EFFECT_TILT_WARNING, SOL_CHIME_100, 4},
  {SOUND_EFFECT_TILT_WARNING, SOL_CHIME_10, 6}
};


struct ChimeEntry MataHariSFXHighPriorityLevel1[] = {
  {SOUND_EFFECT_ADD_CREDIT, SOL_CHIME_10000, 0},
  {SOUND_EFFECT_ADD_CREDIT, SOL_CHIME_10, 2},
  {SOUND_EFFECT_ADD_CREDIT, SOL_CHIME_100, 4},
  {SOUND_EFFECT_ADD_CREDIT, SOL_CHIME_1000, 6},
  {SOUND_EFFECT_ADD_PLAYER, SOL_CHIME_10000, 0},
  {SOUND_EFFECT_ADD_PLAYER, SOL_CHIME_10, 0},
  {SOUND_EFFECT_ADD_PLAYER, SOL_CHIME_1000, 4},
  {SOUND_EFFECT_PLAYER_UP, SOL_CHIME_10, 0},
  {SOUND_EFFECT_PLAYER_UP, SOL_CHIME_100, 0},
  {SOUND_EFFECT_PLAYER_UP, SOL_CHIME_100, 3},
  {SOUND_EFFECT_PLAYER_UP, SOL_CHIME_1000, 3},
  {SOUND_EFFECT_BALL_OVER, SOL_CHIME_10000, 0},
  {SOUND_EFFECT_BALL_OVER, SOL_CHIME_10000, 3},
  {SOUND_EFFECT_GAME_OVER, SOL_CHIME_1000, 0},
  {SOUND_EFFECT_GAME_OVER, SOL_CHIME_1000, 1},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_10000, 0},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_10000, 2},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_10, 4}
};


struct ChimeEntry MataHariSFXHighPriorityLevel2[] = {
  {SOUND_EFFECT_ADD_PLAYER, SOL_CHIME_100, 6},
  {SOUND_EFFECT_ADD_PLAYER, SOL_CHIME_1000, 9},
  {SOUND_EFFECT_ADD_PLAYER, SOL_CHIME_100, 11},
  {SOUND_EFFECT_PLAYER_UP, SOL_CHIME_1000, 6},
  {SOUND_EFFECT_PLAYER_UP, SOL_CHIME_10000, 6},
  {SOUND_EFFECT_BALL_OVER, SOL_CHIME_10, 5},
 // {SOUND_EFFECT_BALL_OVER, SOL_CHIME_10, 15},
 // {SOUND_EFFECT_BALL_OVER, SOL_CHIME_100, 17},
 // {SOUND_EFFECT_BALL_OVER, SOL_CHIME_1000, 20},
 // {SOUND_EFFECT_BALL_OVER, SOL_CHIME_100, 23},
 // {SOUND_EFFECT_BALL_OVER, SOL_CHIME_1000, 25}, 
  {SOUND_EFFECT_GAME_OVER, SOL_CHIME_1000, 3},
  {SOUND_EFFECT_GAME_OVER, SOL_CHIME_100, 4},
  {SOUND_EFFECT_GAME_OVER, SOL_CHIME_10, 5},
  {SOUND_EFFECT_GAME_OVER, SOL_CHIME_10000, 6},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_10000, 6},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_10, 8},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_100, 10},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_10, 12},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_10, 18},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_10, 20},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_100, 22},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_10, 24},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_100, 26},
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_1000, 28}, 
  {SOUND_EFFECT_MACHINE_START, SOL_CHIME_100, 30}
};
